[information]
name = "pop-theme"
background = "dark"
author = 'Eric Henry <erichenryterm@gmail.com>'

# fg = '#DEDEDE'
# bg = '#3F3B39'
#
# white = '#ffffff'
# black = '#00000050'
# light_gray = '#EEFFFF'
# orange = '#f15d22'
# light_orange = '#F78C6C'
# brown = '#C17E70'
# yellow = '#FFCB6B'
# light_yellow = '#ffc977'
# dark_gold = '#FAA41A'
# gold = '#FFCA40'
# blue = '#89DDFF'
# light_blue = '#B2CCD6'
# green = '#73c48f'
# light_green = '#8BCED6'
# pale_green = '#a0b4a7'
#
# info_blue = '#6796e6'
# error_red = '#F44747'
# warning_yellow = '#cd9731'
# debug_purple = '#b267e6'
#
# cursor_fg = '#DEDEDE'
# cursor_bg = '#AEAFAD'

[palette]

alt_fg = '#8b92a8'
alt_bg = '#1b1f27'
dark = '#1b1f27'
accent = '#545862'
popup_back = '#1e222a'
search_orange = '#613214'
line = '#282C34'

search_blue = '#083C5A'
gray = '#545862'
dark_gray = '#3e4451'
context = '#6b737f'
tree_gray = '#1b1f27'
vivid_blue = '#4FC1FF'
dark_blue = '#223E55'
folder_blue = '#42A5F5'
cyan = '#46a6b2'
red = '#d05c65'
light_red = '#d05c65'
purple = '#b668cd'
magenta = '#D16D9E'

# updated
fg = '#DEDEDE'
bg = '#3F3B39'

white = '#ffffff'
black = '#00000050'
light_gray = '#EEFFFF'
orange = '#f15d22'
light_orange = '#F78C6C'
brown = '#C17E70'
yellow = '#FFCB6B'
light_yellow = '#ffc977'
dark_gold = '#FAA41A'
gold = '#FFCA40'
blue = '#89DDFF'
light_blue = '#B2CCD6'
green = '#73c48f'
light_green = '#8BCED6'
pale_green = '#a0b4a7'

info_blue = '#6796e6'
error_red = '#F44747'
warning_yellow = '#cd9731'
debug_purple = '#b267e6'

cursor_fg = '#DEDEDE'
cursor_bg = '#AEAFAD'
# updated end


sign_add = '#587c0c'
sign_change = '#0c7d9d'
sign_delete = '#94151b'
tree_sign_add = '#73C991'
tree_sign_change = '#CCA700'

info_yellow = '#FFCC66'
hint_blue = '#4FC1FF'
success_green = '#14C50B'

purple_test = '#ff007c'
cyan_test = '#00dfff'

ui_blue = '#264F78'
ui2_blue = '#042E48'
ui3_blue = '#0195F7'
ui4_blue = '#75BEFF'
ui_orange = '#E8AB53'
ui_purple = '#B180D7'

[highlights]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg dark'
MsgSeparator = 'fg bg'
SpellBad = 'light_red - u'
SpellCap = 'yellow - u'
SpellLocal = 'green - u'
SpellRare = 'purple - u'
NormalNC = 'fg bg'
Pmenu = 'light_gray tree_gray - - 50'
PmenuSel = '- ui2_blue'
WildMenu = 'fg ui2_blue'
CursorLineNr = 'light_gray - b'
Comment = 'gray - i'
Folded = 'accent alt_bg'
FoldColumn = 'accent alt_bg'
LineNr = 'gray -'
FloatBorder = 'gray alt_bg'
Whitespace = 'bg -'
VertSplit = 'gray bg'
CursorLine = '- dark'
CursorColumn = '- dark'
ColorColumn = '- dark'
NormalFloat = '- dark'
Visual = '- ui_blue'
VisualNOS = '- alt_bg'
WarningMsg = 'error_red bg'
DiffAdd = 'alt_bg sign_add'
DiffChange = 'alt_bg sign_change u'
DiffDelete = 'alt_bg sign_delete'
QuickFixLine = '- ui2_blue'
PmenuSbar = '- alt_bg'
PmenuThumb = '- gray'
MatchWord = '- - u'
MatchParen = 'hint_blue bg u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'accent'
Directory = 'blue'
SpecialKey = 'blue - b'
Title = 'blue - b'
ErrorMsg = 'error_red bg b'
Search = 'light_gray search_blue'
IncSearch = 'search_orange light_gray'
Substitute = 'light_gray search_orange'
MoreMsg = 'orange'
Question = 'orange'
EndOfBuffer = 'bg'
NonText = 'bg'
Variable = 'orange'
String = 'green'
Character = 'orange'
Constant = 'vivid_blue'
Number = 'light_orange'
Boolean = 'blue'
Float = 'light_green'
Identifier = 'light_blue'
Function = 'blue'
Operator = 'blue'
Type = 'light_blue'
StorageClass = 'yellow'
Structure = 'blue'
Typedef = 'blue'
Keyword = 'light_yellow'
Statement = 'purple'
Conditional = 'blue'
Repeat = 'purple'
Label = 'purple'
Exception = 'purple'
Include = 'purple'
PreProc = 'purple'
Define = 'purple'
Macro = 'purple'
PreCondit = 'purple'
Special = 'orange'
SpecialChar = 'white'
Tag = 'orange'
Debug = 'red'
Delimiter = 'gray -'
SpecialComment = 'gray'
Underlined = '- - u'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan bg b'
Todo = 'magenta bg b'
Error = 'error_red bg b'
TabLine = 'light_gray line'
TabLineSel = 'white line'
TabLineFill = 'line line'

[Treesitter]
TSComment = 'link:Comment'
TSAnnotation = 'blue'
TSAttribute = 'light_yellow'
TSConstructor = 'cyan'
TSType = 'cyan'
TSTypeBuiltin = 'orange'
TSConditional = 'yellow'
TSException = 'purple'
TSInclude = 'purple'
TSKeywordReturn = 'light_yellow'
TSKeyword = 'light_yellow'
TSKeywordFunction = 'blue'
TSLabel = 'light_blue'
TSNamespace = 'cyan'
TSRepeat = 'yellow'
TSConstant = 'orange'
TSConstBuiltin = 'orange'
TSFloat = 'orange'
TSNumber = 'light_orange'
TSBoolean = 'orange'
TSCharacter = 'green'
TSError = 'error_red'
TSFunction = 'blue'
TSFuncBuiltin = 'blue'
TSMethod = 'orange'
TSConstMacro = 'orange'
TSFuncMacro = 'blue'
TSVariable = 'orange'
TSVariableBuiltin = 'orange'
TSProperty = 'red'
TSField = 'fg'
TSParameter = 'red'
TSParameterReference = 'red'
TSSymbol = 'light_blue'
TSText = 'alt_fg'
TSOperator = 'alt_fg'
TSPunctDelimiter = 'alt_fg -'
TSTagDelimiter = 'alt_fg'
TSTagAttribute = 'light_yellow'
TSPunctBracket = 'alt_fg -'
TSPunctSpecial = 'purple'
TSString = 'green'
TSStringRegex = 'blue'
TSStringEscape = 'blue'
TSTag = 'blue'
TSEmphasis = '- - i'
TSUnderline = '- - u'
TSTitle = 'fg - -'
TSLiteral = 'orange'
TSURI = 'orange - u'
TSKeywordOperator = 'blue'
TSStructure = 'light_blue'
TSStrong = 'blue - b'
TSQueryLinterError = 'warning_yellow'
TreesitterContext = '- tree_gray'

[markdown]
markdownBlockquote = 'green'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'green'
markdownH2 = 'green'
markdownH3 = 'green'
markdownH4 = 'green'
markdownH5 = 'green'
markdownH6 = 'green'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'fg - b'
markdownId = 'purple'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_gray'
markdownLinkDelimiter = 'light_gray'
markdownBold = 'orange - b'
markdownItalic = 'orange - i'
markdownBoldItalic = 'orange - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'blue'
markdownRule = 'accent'
markdownUrl = 'cyan - u'
markdownLinkText = 'light_green'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'light_blue'
WhichKeyFloat = '- dark'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[LSP]
LspDiagnosticsDefaultError = 'error_red'
LspDiagnosticsDefaultWarning = 'warning_yellow'
LspDiagnosticsDefaultInformation = 'info_blue'
LspDiagnosticsDefaultInfo = 'info_blue'
LspDiagnosticsDefaultHint = 'hint_blue'
LspDiagnosticsVirtualTextError = 'error_red'
LspDiagnosticsVirtualTextWarning = 'warning_yellow'
LspDiagnosticsVirtualTextInformation = 'info_blue'
LspDiagnosticsVirtualTextInfo = 'info_blue'
LspDiagnosticsVirtualTextHint = 'hint_blue'
LspDiagnosticsFloatingError = 'error_red'
LspDiagnosticsFloatingWarning = 'warning_yellow'
LspDiagnosticsFloatingInformation = 'info_blue'
LspDiagnosticsFloatingInfo = 'info_blue'
LspDiagnosticsFloatingHint = 'hint_blue'
DiagnosticSignError = 'error_red'
DiagnosticSignWarning = 'warning_yellow'
DiagnosticSignInformation = 'info_blue'
DiagnosticSignInfo = 'info_blue'
DiagnosticSignHint = 'hint_blue'
LspDiagnosticsSignError = 'error_red'
LspDiagnosticsSignWarning = 'warning_yellow'
LspDiagnosticsSignInformation = 'info_blue'
LspDiagnosticsSignInfo = 'info_blue'
LspDiagnosticsSignHint = 'hint_blue'
LspDiagnosticsError = 'error_red'
LspDiagnosticsWarning = 'warning_yellow'
LspDiagnosticsInformation = 'info_blue'
LspDiagnosticsInfo = 'info_blue'
LspDiagnosticsHint = 'hint_blue'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- #2e303b'
LspReferenceText = '- #2e303b'
LspReferenceWrite = '- #2e303b'
LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Telescope]
TelescopeSelection = 'hint_blue'
TelescopeMatching = 'info_blue - b'
TelescopeBorder = 'blue bg'

[NvimTree]
NvimTreeFolderIcon = 'folder_blue'
NvimTreeIndentMarker = '#c5c5c5'
NvimTreeNormal = 'light_gray tree_gray'
NvimTreeVertSplit = 'alt_bg alt_bg'
NvimTreeFolderName = 'folder_blue'
NvimTreeOpenedFolderName = 'folder_blue - bi'
NvimTreeEmptyFolderName = 'gray - i'
NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'light_gray'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'tree_gray'
NvimTreeCursorLine = '- #282b37'
NvimTreeGitignoreIcon = '#E64A19'
NvimTreeGitStaged = 'tree_sign_add'
NvimTreeGitNew = 'tree_sign_add'
NvimTreeGitRenamed = 'tree_sign_add'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'tree_sign_change'
NvimTreeGitDirty = 'tree_sign_change'

NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = '#9FBA89'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'info_blue bg'
BufferCurrentSign = 'hint_blue bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'info_blue bg'
BufferVisibleSign = 'gray bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'gray alt_bg'
BufferInactiveIndex = 'gray alt_bg'
BufferInactiveMod = 'info_blue alt_bg'
BufferInactiveSign = 'gray alt_bg'
BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
StatusLine = 'line gray'
StatusLineNC = 'line gray'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'dark_gray'
IndentBlanklineSpaceChar = 'cyan_test'
IndentBlanklineSpaceCharBlankline = 'info_blue'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbrDeprecated = 'gray - s'
CmpItemAbbrMatch = 'ui3_blue'
CmpItemAbbrMatchFuzzy = 'ui3_blue'
CmpItemKindFunction = 'blue'
CmpItemKindMethod = 'orange'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'yellow'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'red'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'orange'
CmpItemKindConstant = 'orange'
CmpItemKindKeyword = 'purple'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'yellow'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'fg'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'red'
